export const PHOTOS_FETCH = 'PHOTOS_FETCH';
export const STORE_PHOTO = 'STORE_PHOTO';
export const START_FETCHING = 'START_FETCHING';
export const DONE_FETCHING = 'DONE_FETCHING';
export const FAIL_FETCHING = 'FAIL_FETCHING';
export const FOCUS_SEARCH = 'FOCUS_SEARCH';
export const STORE_FILTERED_RESULTS = 'STORE_FILTERED_RESULTS';
